// <auto-generated />
namespace AzureLogsViewer.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SlackIntegration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SlackIntegration));
        
        string IMigrationMetadata.Id
        {
            get { return "201505032245558_SlackIntegration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
